### ISSUE TITLE
Playground execution failed

### ISSUE THREAD

**Issue by ghost** [JohnSundell/UnboxDemoPlayground#1]
I have this error. Similar to what [this guy](http://stackoverflow.com/questions/36672834/playground-execution-failed-error-couldnt-lookup-symbols) has

```
Playground execution failed: error: Couldn't lookup symbols:
  __TIF4Wrap4WrapurFzTx14writingOptionsGSqVSC20NSJSONWritingOptions_13dateFormatterGSqCSo15NSDateFormatter__CSo6NSDataA1_
  __TF4Wrap4WrapurFzTx14writingOptionsGSqVSC20NSJSONWritingOptions_13dateFormatterGSqCSo15NSDateFormatter__CSo6NSData
  __TIF4Wrap4WrapurFzTx14writingOptionsGSqVSC20NSJSONWritingOptions_13dateFormatterGSqCSo15NSDateFormatter__CSo6NSDataA0_
```

**Comment by JohnSundell** [comment]
Hi @rob-nash! That sounds like a very mysterious error 😓
Some quick questions so that we can start diagnosing the problem:
- Have you updated submodules so that both Unbox & Wrap have been downloaded? 
- Do both Unbox & Wrap show up in the Playground workspace?
- You are using the Workspace, not the direct Playground file, right?
- Have you tried manually pausing and replaying the Playground?

Sorry if the above seems silly, just wanted to double check :)

**Comment by JohnSundell** [comment]
Also try to build both Unbox & Wrap from within the Playground workspace, by selecting their respective schemes (for iOS) and building.

**Comment by ghost** [comment]
Yes to all questions :(

**Comment by JohnSundell** [comment]
@rob-nash Quick follow up question, have you tried to marking the schemes for both Unbox & Wrap in the workspace and pressing `cmd + B` to build them? I just encountered a similar problem with another playground, and that solved it for me.

**Comment by ghost** [comment]
Yep that did it. Thanks :)
